  // status 4- incomplete, 5- failed 7- recovered
export const ApplicationListData = [
    {
      applicationNo: 11189911,
      creationDate: "Dec 13, 2024",
      agentName: "Sufomi Takashi",
      productName: "GASA",
      premium: 1000,
      premiumCurrency: "USD",
      payYears: 12,
      status: 4,
      channel: 1,
    },
    {
      applicationNo: 1111611,
      creationDate: "Dec 13, 2024",
      agentName: "Sufomi Takashi",
      productName: "GASA",
      premium: 1000,
      premiumCurrency: "USD",
      payYears: 12,
      status: 5,
      channel: 3,
    },
    {
      applicationNo: 11111112,
      creationDate: "Dec 13, 2024",
      agentName: "Sufomi Takashi",
      productName: "GASA",
      premium: 1000,
      premiumCurrency: "USD",
      payYears: 12,
      status: 4,
      channel: 1,
    },
    {
      applicationNo: 122111112,
      creationDate: "Dec 13, 2024",
      agentName: "Sufomi Takashi",
      productName: "GASA",
      premium: 1000,
      premiumCurrency: "USD",
      payYears: 12,
      status: 5,
      channel: 1,
    },
    {
        applicationNo: 11118885,
        creationDate: "Dec 13, 2024",
        agentName: "Sufomi Takashi",
        productName: "GASA",
        premium: 1000,
        premiumCurrency: "USD",
        payYears: 12,
        status: 5,
        channel: 3,
      },
      {
        applicationNo: 11118886,
        creationDate: "Dec 13, 2024",
        agentName: "Sufomi Takashi",
        productName: "GASA",
        premium: 1000,
        premiumCurrency: "USD",
        payYears: 12,
        status: 7,
        channel: 1,
      },
      {
        applicationNo: 11118887,
        creationDate: "Dec 13, 2024",
        agentName: "Sufomi Takashi",
        productName: "GASA",
        premium: 1000,
        premiumCurrency: "USD",
        payYears: 12,
        status: 5,
        channel: 3,
      },
      {
        applicationNo: 11118888,
        creationDate: "Dec 13, 2024",
        agentName: "Sufomi Takashi",
        productName: "GASA",
        premium: 1000,
        premiumCurrency: "USD",
        payYears: 12,
        status: 7,
        channel: 1,
      },
  ];